sudo: false
language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py,coverage,flake8
    - python: 3.5
      env: TOXENV=py,coverage,flake8
    - python: 3.4
      env: TOXENV=py,coverage,flake8
    - python: 3.3
      env: TOXENV=py,coverage,flake8
    - python: 2.7
      env: TOXENV=py,coverage,flake8

install: 
  - pip install tox

script:
  - tox

cache: 
  - pip

branches:
    only:
        - master
